# Generated by Django 5.2.6 on 2025-09-13 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('prior_highest_education', models.CharField(choices=[('NO EDUCATION', 'No Education'), ('HIGH SCHOOL', 'High School'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'PhD')], default='NO EDUCATION', max_length=32)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certifcates/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
