# Generated by Django 5.2.6 on 2025-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cover_letter',
            new_name='essay',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate',
        ),
        migrations.AddField(
            model_name='application',
            name='education_document',
            field=models.ImageField(blank=True, null=True, upload_to='education_document/'),
        ),
        migrations.AddField(
            model_name='application',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='recommendation_letter/'),
        ),
    ]
