# Generated by Django 5.2.6 on 2025-09-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_cover_letter_application_essay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education_document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
