# Generated by Django 5.2.6 on 2025-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_education_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education_document',
            field=models.FileField(blank=True, null=True, upload_to='education_docs/'),
        ),
    ]
