# Generated by Django 5.2.6 on 2025-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_education_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('WHITE LISTED', 'Waitlisted'), ('UNDER REVIEW', 'Under Review'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=32),
        ),
    ]
