# Generated by Django 5.2.6 on 2025-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='target_program',
            field=models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], default='BACHELOR', max_length=32),
        ),
    ]
