# Generated by Django 5.2.6 on 2025-09-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_target_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='prior_highest_education',
            field=models.CharField(choices=[('NO EDUCATION', 'No Education'), ('MIDDLE SCHOOL', 'Middle School'), ('HIGH SCHOOL', 'High School'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], default='NO EDUCATION', max_length=32),
        ),
    ]
