# Generated by Django 5.2.6 on 2025-09-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_established_university_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
